// Generated by https://quicktype.io

import 'dart:convert';

import 'package:practica2/src/models/news%20models/id_model.dart';

class DetailNewsModel {
  NewsSourceModel? source;
  String? author;
  String? title;
  String? description;
  String? url;
  String? urlToImage;
  String? publishedAt;
  String? content;

  DetailNewsModel({
    this.source,
    this.author,
    this.title,
    this.description,
    this.url,
    this.urlToImage,
    this.publishedAt,
    this.content,
  });

   factory DetailNewsModel.fromJson(Map<String, dynamic> json) {
    return DetailNewsModel(
      source: NewsSourceModel.fromJson(json['source']),
      author: json['author'] ,
      title: json['title'] ,
      description: json['description'] ,
      url: json['url'] ,
      urlToImage: json['urlToImage'] ?? "" ,
      publishedAt: json['publishedAt'] ,
      content: json['content'] ,
    );
  }


}
